// frontend/src/pages/BoasVindas.tsx
import { Link } from 'react-router-dom';
import './BoasVindas.css';

export function BoasVindas() {
  return (
    <div className="aviso">
      <div className="aviso__ilustracao">
        <svg width="220" height="150" viewBox="0 0 220 150" fill="none" xmlns="http://www.w3.org/2000/svg">
          <ellipse cx="110" cy="138" rx="90" ry="8" fill="#eaf1fc" />
          {/* poste da parada */}
          <rect x="30" y="40" width="4" height="90" rx="2" fill="#c7d4ea" />
          <rect x="18" y="30" width="28" height="16" rx="4" fill="#1e4d94" />
          <rect x="22" y="34" width="20" height="3" rx="1.5" fill="#fff" />
          <rect x="22" y="39" width="14" height="3" rx="1.5" fill="#fff" />
          {/* pessoa */}
          <circle cx="95" cy="70" r="11" fill="#1e4d94" />
          <path d="M78 130v-30c0-10 8-18 17-18s17 8 17 18v30" fill="#2fa360" />
          {/* balão de fala */}
          <rect x="118" y="42" width="80" height="34" rx="12" fill="#fff" stroke="#e7ebf3" strokeWidth="2" />
          <path d="M128 76l-8 12 16-8z" fill="#fff" stroke="#e7ebf3" strokeWidth="2" />
          <circle cx="134" cy="59" r="6" fill="#34a853" />
          <path d="M131.5 59l1.8 2 3.2-4" stroke="#fff" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
          <text x="148" y="63" fontFamily="Poppins, sans-serif" fontSize="12" fontWeight="700" fill="#1b2333">
            ETA: 5 min
          </text>
        </svg>
      </div>

      <h1>
        Entenda o SmartBus
        <br />
        Santo André
      </h1>

      <ul className="aviso__passos">
        <li>
          <span className="aviso__icone">📍</span>
          Veja o ônibus no mapa
        </li>
        <li>
          <span className="aviso__icone">⏱️</span>
          Verifique o tempo e lotação
        </li>
        <li>
          <span className="aviso__icone">📣</span>
          Colabore e informe
        </li>
      </ul>

      <p className="aviso__legenda">Rastreamento em tempo real e lotação colaborativa na sua cidade.</p>

      <Link to="/login" className="btn btn--primario">
        COMEÇAR VIAGEM
      </Link>
      <p className="aviso__rodape">
        Já tem conta? <Link to="/login">Entrar</Link> · <Link to="/registro">Criar conta</Link>
      </p>
    </div>
  );
}

// frontend/src/app/features/boas-vindas/boas-vindas.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-boas-vindas',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="aviso">
      <div class="aviso__ilustracao">
        <svg width="120" height="120" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <circle cx="12" cy="12" r="12" fill="#eaf1fc"/>
          <rect x="5" y="9" width="14" height="9" rx="3" fill="#1e4d94"/>
          <circle cx="8.5" cy="18.5" r="1.5" fill="#133769"/>
          <circle cx="15.5" cy="18.5" r="1.5" fill="#133769"/>
          <path d="M7 12.5h10M7 15.5h6" stroke="#fff" stroke-width="1.2" stroke-linecap="round"/>
          <path d="M7 6.5 9 9M17 6.5 15 9" stroke="#2fa360" stroke-width="1.4" stroke-linecap="round"/>
        </svg>
      </div>

      <h1>Entenda o SmartBus<br />Santo André</h1>

      <ul class="aviso__passos">
        <li>
          <span class="aviso__icone">📍</span>
          Veja o ônibus no mapa
        </li>
        <li>
          <span class="aviso__icone">⏱️</span>
          Verifique o tempo e lotação
        </li>
        <li>
          <span class="aviso__icone">📣</span>
          Colabore e informe
        </li>
      </ul>

      <p class="aviso__legenda">
        Rastreamento em tempo real e lotação colaborativa na sua cidade.
      </p>

      <a routerLink="/login" class="btn btn--primario">COMEÇAR VIAGEM</a>
      <p class="aviso__rodape">
        Já tem conta? <a routerLink="/login">Entrar</a> · <a routerLink="/registro">Criar conta</a>
      </p>
    </div>
  `,
  styleUrl: './boas-vindas.component.scss'
})
export class BoasVindasComponent {}
