// frontend/src/app/shared/components/header/header.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule],
  template: `
    <header class="app-header">
      <span class="app-header__titulo">{{ titulo }}</span>
      @if (auth.autenticado()) {
        <button class="app-header__sair" (click)="sair()" aria-label="Sair">Sair</button>
      }
    </header>
  `,
  styleUrl: './header.component.scss'
})
export class HeaderComponent {
  @Input() titulo = 'SmartBus';

  constructor(public auth: AuthService, private router: Router) {}

  sair(): void {
    this.auth.logout();
    this.router.navigate(['/boas-vindas']);
  }
}

// frontend/src/components/Header.tsx
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../lib/auth';
import './Header.css';

export function Header({ titulo = 'SmartBus' }: { titulo?: string }) {
  const { autenticado, logout } = useAuth();
  const navigate = useNavigate();

  function sair() {
    logout();
    navigate('/boas-vindas');
  }

  return (
    <header className="app-header">
      <span className="app-header__titulo">{titulo}</span>
      {autenticado && (
        <button className="app-header__sair" onClick={sair} aria-label="Sair">
          Sair
        </button>
      )}
    </header>
  );
}
