// frontend/src/pages/Registro.tsx
import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../lib/auth';
import './Auth.css';

export function Registro() {
  const [nome, setNome] = useState('');
  const [email, setEmail] = useState('');
  const [senha, setSenha] = useState('');
  const [erro, setErro] = useState('');
  const [carregando, setCarregando] = useState(false);
  const { registrar } = useAuth();
  const navigate = useNavigate();

  async function criarConta(e: FormEvent) {
    e.preventDefault();
    setCarregando(true);
    setErro('');
    try {
      await registrar({ nome, email, senha });
      navigate('/principal');
    } catch {
      setErro('Não foi possível criar sua conta. Verifique os dados.');
    } finally {
      setCarregando(false);
    }
  }

  return (
    <div className="auth-page">
      <h1>Criar conta</h1>
      <form onSubmit={criarConta}>
        <label>
          Nome completo
          <input
            type="text"
            required
            placeholder="Seu nome"
            value={nome}
            onChange={(e) => setNome(e.target.value)}
          />
        </label>
        <label>
          E-mail acadêmico
          <input
            type="email"
            required
            placeholder="voce@fsa.edu.br"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
        </label>
        <label>
          Senha
          <input
            type="password"
            required
            minLength={6}
            placeholder="mínimo 6 caracteres"
            value={senha}
            onChange={(e) => setSenha(e.target.value)}
          />
        </label>

        {erro && <p className="erro">{erro}</p>}

        <button className="btn" type="submit" disabled={carregando}>
          {carregando ? 'Criando...' : 'Criar conta'}
        </button>
      </form>
      <p className="auth-page__rodape">
        Já tem conta? <Link to="/login">Entrar</Link>
      </p>
    </div>
  );
}

// frontend/src/app/features/registro/registro.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-registro',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  template: `
    <div class="auth-page">
      <h1>Criar conta</h1>
      <form [formGroup]="form" (ngSubmit)="registrar()">
        <label>
          Nome completo
          <input type="text" formControlName="nome" placeholder="Seu nome" />
        </label>
        <label>
          E-mail acadêmico
          <input type="email" formControlName="email" placeholder="voce@fsa.edu.br" />
        </label>
        <label>
          Senha
          <input type="password" formControlName="senha" placeholder="mínimo 6 caracteres" />
        </label>

        @if (erro) {
          <p class="erro">{{ erro }}</p>
        }

        <button class="btn btn--primario" type="submit" [disabled]="form.invalid || carregando">
          {{ carregando ? 'Criando...' : 'Criar conta' }}
        </button>
      </form>
      <p class="auth-page__rodape">
        Já tem conta? <a routerLink="/login">Entrar</a>
      </p>
    </div>
  `,
  styleUrl: './registro.component.scss'
})
export class RegistroComponent {
  erro = '';
  carregando = false;
  form: ReturnType<FormBuilder['group']>;

  constructor(private fb: FormBuilder, private auth: AuthService, private router: Router) {
    this.form = this.fb.group({
      nome: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      senha: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  registrar(): void {
    if (this.form.invalid) return;
    this.carregando = true;
    this.erro = '';

    this.auth
      .registrar({
        nome: this.form.value.nome!,
        email: this.form.value.email!,
        senha: this.form.value.senha!
      })
      .subscribe({
        next: () => this.router.navigate(['/principal']),
        error: () => {
          this.erro = 'Não foi possível criar sua conta. Verifique os dados.';
          this.carregando = false;
        }
      });
  }
}
