// frontend/src/app/features/reportar-lotacao/reportar-lotacao.component.ts
import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import * as L from 'leaflet';
import { LinhaService } from '../../core/services/linha.service';
import { RotaService } from '../../core/services/rota.service';
import { ReporteService } from '../../core/services/reporte.service';
import { AuthService } from '../../core/services/auth.service';
import { Linha, NivelLotacao } from '../../core/models/linha.model';

const CENTRO_PADRAO: [number, number] = [-23.6547, -46.5382];

@Component({
  selector: 'app-reportar-lotacao',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <main class="reportar">
      <button class="voltar" (click)="voltar()" aria-label="Voltar">‹</button>

      <div #mapaEl class="reportar__mapa"></div>

      <section class="painel">
        <h2>Como está sua viagem{{ auth.usuario()?.nome ? ', ' + auth.usuario()?.nome : '' }}?</h2>

        <label class="reportar__campo">
          <select [(ngModel)]="linhaSelecionadaId" name="linha" (ngModelChange)="onLinhaAlterada()">
            <option [ngValue]="null" disabled>Selecione a linha</option>
            @for (linha of linhas; track linha.id) {
              <option [ngValue]="linha.id">{{ linha.codigo }} · {{ linha.nome }}</option>
            }
          </select>
        </label>

        <div class="opcoes-lotacao">
          <button
            type="button"
            class="opcao opcao--verde"
            [class.selecionada]="nivelSelecionado === NivelLotacao.Vazio"
            (click)="nivelSelecionado = NivelLotacao.Vazio"
          >
            <span class="opcao__icone">🟢</span>
            Muitos assentos livres
          </button>
          <button
            type="button"
            class="opcao opcao--amarelo"
            [class.selecionada]="nivelSelecionado === NivelLotacao.ComLugares"
            (click)="nivelSelecionado = NivelLotacao.ComLugares"
          >
            <span class="opcao__icone">🟡</span>
            Poucos assentos livres
          </button>
          <button
            type="button"
            class="opcao opcao--vermelho"
            [class.selecionada]="nivelSelecionado === NivelLotacao.SuperLotado"
            (click)="nivelSelecionado = NivelLotacao.SuperLotado"
          >
            <span class="opcao__icone">🔴</span>
            Todos em pé / Lotado
          </button>
        </div>

        @if (erro) {
          <p class="erro">{{ erro }}</p>
        }

        <button
          class="btn btn--primario"
          [disabled]="linhaSelecionadaId == null || nivelSelecionado == null || enviando"
          (click)="enviar()"
        >
          {{ enviando ? 'Enviando...' : 'Enviar Reporte' }}
        </button>
      </section>
    </main>
  `,
  styleUrl: './reportar-lotacao.component.scss'
})
export class ReportarLotacaoComponent implements AfterViewInit, OnDestroy {
  @ViewChild('mapaEl') mapaEl!: ElementRef<HTMLDivElement>;

  linhas: Linha[] = [];
  linhaSelecionadaId: number | null = null;
  nivelSelecionado: NivelLotacao | null = null;
  NivelLotacao = NivelLotacao;
  erro = '';
  enviando = false;
  private mapa?: L.Map;

  constructor(
    private linhaService: LinhaService,
    private rotaService: RotaService,
    private reporteService: ReporteService,
    private route: ActivatedRoute,
    private router: Router,
    public auth: AuthService
  ) {}

  ngAfterViewInit(): void {
    this.mapa = L.map(this.mapaEl.nativeElement).setView(CENTRO_PADRAO, 14);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; OpenStreetMap contributors',
      maxZoom: 19
    }).addTo(this.mapa);

    this.linhaService.listar().subscribe((linhas) => {
      this.linhas = linhas;
      const linhaIdQuery = this.route.snapshot.queryParamMap.get('linhaId');
      if (linhaIdQuery) {
        this.linhaSelecionadaId = Number(linhaIdQuery);
        this.onLinhaAlterada();
      }
    });
  }

  onLinhaAlterada(): void {
    if (this.linhaSelecionadaId == null || !this.mapa) return;

    this.rotaService.obterPorLinha(this.linhaSelecionadaId).subscribe((rota) => {
      this.mapa!.eachLayer((camada) => {
        if (!(camada instanceof L.TileLayer)) this.mapa!.removeLayer(camada);
      });

      const paradasOrdenadas = [...rota.paradas].sort((a, b) => a.ordem - b.ordem);
      const pontos = paradasOrdenadas.map((p) => [p.latitude, p.longitude] as [number, number]);

      paradasOrdenadas.forEach((parada) => {
        L.marker([parada.latitude, parada.longitude]).addTo(this.mapa!).bindPopup(parada.nome);
      });

      if (pontos.length > 1) {
        L.polyline(pontos, { color: '#1e4d94', weight: 4 }).addTo(this.mapa!);
        this.mapa!.fitBounds(L.latLngBounds(pontos), { padding: [24, 24] });
      }
    });
  }

  enviar(): void {
    if (this.linhaSelecionadaId == null || this.nivelSelecionado == null) return;
    this.enviando = true;
    this.erro = '';

    const concluir = (latitude?: number, longitude?: number) => {
      this.reporteService
        .enviar({
          linhaId: this.linhaSelecionadaId!,
          nivelLotacao: this.nivelSelecionado!,
          latitude,
          longitude
        })
        .subscribe({
          next: () => this.router.navigate(['/confirmacao']),
          error: () => {
            this.erro = 'Não foi possível enviar seu reporte. Tente novamente.';
            this.enviando = false;
          }
        });
    };

    if ('geolocation' in navigator) {
      navigator.geolocation.getCurrentPosition(
        (posicao) => concluir(posicao.coords.latitude, posicao.coords.longitude),
        () => concluir(undefined, undefined)
      );
    } else {
      concluir(undefined, undefined);
    }
  }

  voltar(): void {
    this.router.navigate(['/linhas']);
  }

  ngOnDestroy(): void {
    this.mapa?.remove();
  }
}

// frontend/src/pages/ReportarLotacao.tsx
import { useEffect, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import * as L from 'leaflet';
import { api } from '../lib/api';
import { useAuth } from '../lib/auth';
import { NivelLotacao, type Linha, type NovoReporte, type Rota } from '../types';
import './ReportarLotacao.css';

const CENTRO_PADRAO: [number, number] = [-23.6547, -46.5382];

export function ReportarLotacao() {
  const mapaRef = useRef<HTMLDivElement>(null);
  const mapaInstancia = useRef<L.Map | null>(null);
  const [linhas, setLinhas] = useState<Linha[]>([]);
  const [searchParams] = useSearchParams();
  const [linhaSelecionadaId, setLinhaSelecionadaId] = useState<number | ''>('');
  const [nivelSelecionado, setNivelSelecionado] = useState<NivelLotacao | null>(null);
  const [erro, setErro] = useState('');
  const [enviando, setEnviando] = useState(false);
  const { usuario } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (!mapaRef.current) return;
    const mapa = L.map(mapaRef.current).setView(CENTRO_PADRAO, 14);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; OpenStreetMap contributors',
      maxZoom: 19
    }).addTo(mapa);
    mapaInstancia.current = mapa;

    api.get<Linha[]>('/linhas').then(({ data }) => {
      setLinhas(data);
      const linhaIdQuery = searchParams.get('linhaId');
      if (linhaIdQuery) {
        setLinhaSelecionadaId(Number(linhaIdQuery));
      }
    });

    return () => {
      mapa.remove();
      mapaInstancia.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    const mapa = mapaInstancia.current;
    if (!mapa || linhaSelecionadaId === '') return;

    api.get<Rota>(`/rotas/${linhaSelecionadaId}`).then(({ data: rota }) => {
      mapa.eachLayer((camada) => {
        if (!(camada instanceof L.TileLayer)) mapa.removeLayer(camada);
      });

      const paradasOrdenadas = [...rota.paradas].sort((a, b) => a.ordem - b.ordem);
      const pontos = paradasOrdenadas.map((p) => [p.latitude, p.longitude] as [number, number]);

      paradasOrdenadas.forEach((parada) => {
        L.marker([parada.latitude, parada.longitude]).addTo(mapa).bindPopup(parada.nome);
      });

      if (pontos.length > 1) {
        L.polyline(pontos, { color: '#1e4d94', weight: 4 }).addTo(mapa);
        mapa.fitBounds(L.latLngBounds(pontos), { padding: [24, 24] });
      }
    });
  }, [linhaSelecionadaId]);

  function obterLocalizacao(): Promise<{ latitude?: number; longitude?: number }> {
    return new Promise((resolve) => {
      if (!('geolocation' in navigator)) {
        resolve({});
        return;
      }
      navigator.geolocation.getCurrentPosition(
        (posicao) => resolve({ latitude: posicao.coords.latitude, longitude: posicao.coords.longitude }),
        () => resolve({})
      );
    });
  }

  async function enviar() {
    if (linhaSelecionadaId === '' || nivelSelecionado == null) return;
    setEnviando(true);
    setErro('');

    try {
      const { latitude, longitude } = await obterLocalizacao();
      const reporte: NovoReporte = {
        linhaId: linhaSelecionadaId,
        nivelLotacao: nivelSelecionado,
        latitude,
        longitude
      };
      await api.post('/reportes', reporte);
      navigate('/confirmacao');
    } catch {
      setErro('Não foi possível enviar seu reporte. Tente novamente.');
    } finally {
      setEnviando(false);
    }
  }

  return (
    <main className="reportar">
      <button className="voltar" onClick={() => navigate('/linhas')} aria-label="Voltar">
        ‹
      </button>

      <div ref={mapaRef} className="reportar__mapa" />

      <section className="painel">
        <h2>Como está sua viagem{usuario?.nome ? `, ${usuario.nome}` : ''}?</h2>

        <label className="reportar__campo">
          <select
            value={linhaSelecionadaId}
            onChange={(e) => setLinhaSelecionadaId(e.target.value ? Number(e.target.value) : '')}
          >
            <option value="" disabled>
              Selecione a linha
            </option>
            {linhas.map((linha) => (
              <option key={linha.id} value={linha.id}>
                {linha.codigo} · {linha.nome}
              </option>
            ))}
          </select>
        </label>

        <div className="opcoes-lotacao">
          <button
            type="button"
            className={`opcao opcao--verde ${nivelSelecionado === NivelLotacao.Vazio ? 'selecionada' : ''}`}
            onClick={() => setNivelSelecionado(NivelLotacao.Vazio)}
          >
            <span className="opcao__icone">🟢</span>
            Muitos assentos livres
          </button>
          <button
            type="button"
            className={`opcao opcao--amarelo ${nivelSelecionado === NivelLotacao.ComLugares ? 'selecionada' : ''}`}
            onClick={() => setNivelSelecionado(NivelLotacao.ComLugares)}
          >
            <span className="opcao__icone">🟡</span>
            Poucos assentos livres
          </button>
          <button
            type="button"
            className={`opcao opcao--vermelho ${nivelSelecionado === NivelLotacao.SuperLotado ? 'selecionada' : ''}`}
            onClick={() => setNivelSelecionado(NivelLotacao.SuperLotado)}
          >
            <span className="opcao__icone">🔴</span>
            Todos em pé / Lotado
          </button>
        </div>

        {erro && <p className="erro">{erro}</p>}

        <button
          className="btn btn--primario"
          disabled={linhaSelecionadaId === '' || nivelSelecionado == null || enviando}
          onClick={enviar}
        >
          {enviando ? 'Enviando...' : 'Enviar Reporte'}
        </button>
      </section>
    </main>
  );
}
